### ISSUE TITLE
Add Achromevement icon

### ISSUE THREAD

**Issue by canhnd58** [canhnd58/achromevement#12]

**Comment by lehainam-dev** [comment]
I come up with this idea.
What do you think?

![icon](https://user-images.githubusercontent.com/12379457/47317036-be2c7300-d672-11e8-9e38-3bb2ae4edd0c.png)

**Comment by canhnd58** [comment]
I think it's good.

*dm đẹp vl*

**Comment by tung-eh** [comment]
@lehainam125 I think it'll be better if we change color of 2 pieces on the bottom to the same color as the border of chrome icon (#4B4B4A)

**Comment by canhnd58** [comment]
Just want to remind that extension icons when loaded on chrome are as small as this <img width="28" alt="screen shot 2018-10-23 at 21 53 37" src="https://user-images.githubusercontent.com/9996596/47369619-46ac2180-d70e-11e8-8d43-6b11db5014e7.png">. When downscaled, the wavy curve looks a little bit too intense and the light colors (in the center) seem to be blended together.

Anyways, I think this icon is good enough. @lehainam125 please refer to [this](https://developer.chrome.com/extensions/browserAction) to add the icon to the project and create a PR.

**Comment by lehainam-dev** [comment]
I created a PR #28.
I also think the icon should be re-designed in the near future. Currently, it's too small compare to other extension's icon.
